In [5]:
from keras.preprocessing.text import Tokenizer
# define 5 documents
docs = ['Well done!',
        'Good work',
        'Great effort',
        'nice work',
        'Excellent!']
# create the tokenizer
t = Tokenizer()
# fit the tokenizer on the documents
t.fit_on_texts(docs)
# summarize what was learned
print(t.word_counts) # object
print(t.document_count)
print(t.word_index)
#print(t.word_index['well'])
print(t.word_docs)
# integer encode documents
encoded_docs = t.texts_to_matrix(docs, mode='count')
print(encoded_docs)

OrderedDict([('well', 1), ('done', 1), ('good', 1), ('work', 2), ('great', 1), ('effort', 1), ('nice', 1), ('excellent', 1)])
5
{'work': 1, 'well': 2, 'done': 3, 'good': 4, 'great': 5, 'effort': 6, 'nice': 7, 'excellent': 8}
{'done': 1, 'well': 1, 'work': 2, 'good': 1, 'great': 1, 'effort': 1, 'nice': 1, 'excellent': 1}
[[0. 0. 1. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [1]:
#http://beanobody.blogspot.tw/2015/06/jieba.html
import jieba
seg_list = jieba.cut("我義守大學的老師", cut_all=False)
print("Default Mode: " + "/ ".join(seg_list))

Building prefix dict from the default dictionary ...
Dumping model to file cache C:\Users\TCFST2D\AppData\Local\Temp\jieba.cache
Loading model cost 0.828 seconds.
Prefix dict has been built succesfully.


Default Mode: 我義守/ 大學/ 的/ 老師


In [2]:
#encoding=utf-8
import jieba
jieba.set_dictionary('dict.txt.big')
content = open('lyric_tw.txt', 'rb').read() #str
#print("Input(unicode):", content)
print("Input(utf-8):", content.decode('utf8'))
words = jieba.cut(content, cut_all=False)
print('Output Full Mode:')
for word in words:
    print(word)
type(word)

Building prefix dict from C:\Users\TCFST2D\Desktop\yllin\Code\Lesson_02\dict.txt.big ...


Input(utf-8): 親愛的媽媽
請你毋通煩惱我
原諒我
行袂開跤
我欲去對抗袂當原諒的人

歹勢啦
愛人啊
袂當陪你去看電影
原諒我
行袂開跤
我欲去對抗欺負咱的人

天色漸漸光
遮有一陣人
為了守護咱的夢
成做更加勇敢的人

天色漸漸光
已經不再驚惶
現在就是彼一工
換阮做守護恁的人

已經袂記
是第幾工
請毋通煩惱我
因為阮知道
無行過寒冬
袂有花開的一工

天色漸漸光
天色漸漸光
已經是更加勇敢的人

天色漸漸光
咱就大聲來唱著歌
一直到希望的光線
照光島嶼每一個人

天色漸漸光
咱就大聲來唱著歌
日頭一爬上山
就會使轉去啦
現在是彼一工
勇敢的台灣人
Output Full Mode:


Dumping model to file cache C:\Users\TCFST2D\AppData\Local\Temp\jieba.u57f102e65df50cc6412ccfb642a275e3.cache
Loading model cost 1.424 seconds.
Prefix dict has been built succesfully.


親愛
的
媽媽


請
你
毋通
煩惱
我


原諒
我


行袂
開跤


我
欲
去
對抗
袂
當
原諒
的
人




歹勢
啦


愛人
啊


袂
當
陪你去
看
電影


原諒
我


行袂
開跤


我
欲
去
對抗
欺負
咱
的
人




天色
漸漸
光


遮有
一陣
人


為
了
守護
咱
的
夢


成
做
更加
勇敢的人




天色
漸漸
光


已經
不再
驚惶


現在
就是
彼一工


換阮
做
守護
恁
的
人




已經
袂
記


是
第幾
工


請
毋通
煩惱
我


因為
阮
知道


無行過
寒冬


袂
有
花開
的
一工




天色
漸漸
光


天色
漸漸
光


已經
是
更加
勇敢的人




天色
漸漸
光


咱
就
大聲
來
唱
著歌


一直
到
希望
的
光線


照光
島嶼
每
一個
人




天色
漸漸
光


咱
就
大聲
來
唱
著歌


日頭
一爬
上山


就
會
使
轉去
啦


現在
是
彼
一工


勇敢
的
台灣
人


str

In [12]:
#encoding=utf-8
import jieba
jieba.set_dictionary('dict.txt.big')
content = open('lyric_tw.txt', 'r', encoding='UTF-8').read() #str
print("Input:", content)
words = jieba.cut(content, cut_all=False)
print('Output Full Mode:')
for word in words:
    print(word)

Building prefix dict from F:\11.Courses\TCFST-9\Code\Lesson_02\dict.txt.big ...
Loading model from cache C:\Users\yllin\AppData\Local\Temp\jieba.u2b2175d96898b6bf076395d98058daa8.cache


Input: 親愛的媽媽
請你毋通煩惱我
原諒我
行袂開跤
我欲去對抗袂當原諒的人

歹勢啦
愛人啊
袂當陪你去看電影
原諒我
行袂開跤
我欲去對抗欺負咱的人

天色漸漸光
遮有一陣人
為了守護咱的夢
成做更加勇敢的人

天色漸漸光
已經不再驚惶
現在就是彼一工
換阮做守護恁的人

已經袂記
是第幾工
請毋通煩惱我
因為阮知道
無行過寒冬
袂有花開的一工

天色漸漸光
天色漸漸光
已經是更加勇敢的人

天色漸漸光
咱就大聲來唱著歌
一直到希望的光線
照光島嶼每一個人

天色漸漸光
咱就大聲來唱著歌
日頭一爬上山
就會使轉去啦
現在是彼一工
勇敢的台灣人
Output Full Mode:


Loading model cost 1.254 seconds.
Prefix dict has been built succesfully.


親愛
的
媽媽


請
你
毋通
煩惱
我


原諒
我


行袂
開跤


我
欲
去
對抗
袂
當
原諒
的
人




歹勢
啦


愛人
啊


袂
當
陪你去
看
電影


原諒
我


行袂
開跤


我
欲
去
對抗
欺負
咱
的
人




天色
漸漸
光


遮有
一陣
人


為
了
守護
咱
的
夢


成
做
更加
勇敢的人




天色
漸漸
光


已經
不再
驚惶


現在
就是
彼一工


換阮
做
守護
恁
的
人




已經
袂
記


是
第幾
工


請
毋通
煩惱
我


因為
阮
知道


無行過
寒冬


袂
有
花開
的
一工




天色
漸漸
光


天色
漸漸
光


已經
是
更加
勇敢的人




天色
漸漸
光


咱
就
大聲
來
唱
著歌


一直
到
希望
的
光線


照光
島嶼
每
一個
人




天色
漸漸
光


咱
就
大聲
來
唱
著歌


日頭
一爬
上山


就
會
使
轉去
啦


現在
是
彼
一工


勇敢
的
台灣
人


In [3]:
#encoding=utf-8
import jieba
import numpy as np
plain_text = []
tokenset = set()
#content = open('lyric.txt', 'r').read()
fin = open('lyric.txt', 'r', encoding='UTF-8')
chinese_punctuations = ['，', '。', '：', '；', '?','（', '）', '「', '」', '！', '“', '”', '\n']
stopwords = ['你','我','他','她','它']
for eachLine in fin:
    tmp_line = []
    tokens = jieba.cut(eachLine)
    for word in tokens:
        if((word not in chinese_punctuations) and (word not in stopwords)):
            tokenset.add(word)
            tmp_line.append(word)
    plain_text.append(tmp_line)
fin.close()
tokenlist = list(tokenset)
print(tokenlist)

['我', '那', '臉孔', '是否', '肌迫', '隨便說說', '如果', '寬闊', '你', '藉口', '只要', '空洞', '不安全感', '熱火', '來說', '自我', '退縮', '怯懦', '遊戲', '勇氣', '\n', '墓誌銘', '地', '把握', '真實', '囉唆', '是', '滿腔', '一場', '一般', '熱情', '的', '一向', '座右銘', '撫摸', '心', '所謂', '和', '力', '消瘦', '滿肚', '順從', '軟弱', '對', '認同感', '雖然', '沒有', '而', '海洋', '逼不得已', '只有', '矯作', '只是', '困惑']
